name: Delete Old Workflow Runs And Deployments

on:
    schedule:
        - cron: "0 0 * * *" # Runs daily at midnight UTC, change as needed

jobs:
    delete_runs:
        runs-on: ubuntu-latest
        permissions:
            actions: write # Needed for deleting runs
        steps:
            - name: Install GitHub CLI
              run: sudo apt-get install gh -y

            - name: Delete workflow runs
              run: |
                  gh run list --limit 100 --json databaseId,createdAt \
                  --jq '.[] | select(.createdAt < (now - 86400 | todate)) | .databaseId' \
                  | xargs -I {} gh run delete {}

              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    delete_deployments:
        runs-on: ubuntu-latest
        permissions:
            deployments: write # Needed for deleting deployments
        steps:
            - name: Install GitHub CLI
              run: sudo apt-get install gh -y

            - name: Get all deployments
              id: get_deployments
              run: |
                  gh api repos/mirkolugano1/liquidation/deployments --jq '.[].id' > deployments.txt

            - name: Get last deployment
              id: get_last_deployment
              run: |
                  LAST_DEPLOYMENT_ID=$(gh api repos/mirkolugano1/liquidation/deployments --jq '.[0].id')
                  echo "LAST_DEPLOYMENT_ID=$LAST_DEPLOYMENT_ID" >> $GITHUB_ENV

            - name: Delete old deployments
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  LAST_DEPLOYMENT_ID: ${{ env.LAST_DEPLOYMENT_ID }}
              run: |
                  cat deployments.txt | while read -r deployment_id; do
                  if [ "$deployment_id" != "$LAST_DEPLOYMENT_ID" ]; then
                      echo "Deleting deployment $deployment_id"
                      gh api -X DELETE "repos/mirkolugano1/liquidation/deployments/$deployment_id"
                  else
                      echo "Skipping last deployment $deployment_id"
                  fi
                  done
