name: Build and deploy Node.js app to Azure Web App - liquidation

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"

            - name: Login to Azure (for tests)
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build:full --if-present
                  npm run test --if-present

            # Option 1: Upload just the dist directory
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Create deployment package
              run: |
                  # Create deployment.zip from the downloaded artifact
                  zip -r deployment.zip .

            - name: Deploy to Azure WebApp
              id: deploy-to-webapp
              shell: bash
              run: |
                  az webapp deploy --resource-group liquidation_group --name liquidation --src-path "./deployment.zip" --type zip
