name: Build and deploy Node.js app to Azure Web App - liquidation

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"

            - name: Login to Azure (for tests)
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Prepare deployment package
              run: |
                  # Create a deployment package excluding node_modules
                  zip -r deployment.zip . -x "node_modules/*" "dist/*" ".git/*"

            # Using the GitHub Action (recommended)
            - uses: azure/webapps-deploy@v2
              with:
                  app-name: liquidation
                  package: "./deployment.zip"
