name: Build and deploy Node.js app to Azure Web App - liquidation

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"
                  cache: "npm" # Enable npm cache

            - name: Install dependencies
              run: npm ci # Use npm ci for faster, more reliable builds

            - name: Build
              run: npm run build

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Prepare deployment package
              run: |
                  # This will zip everything except node_modules and common exclude patterns
                  zip -r deployment.zip . -x "node_modules/*" "dist/*" ".git/*" "*.log" "*.md" "README.md" "LICENSE" ".github/*" ".vscode/*" "tests/*" "test/*" "*.spec.js" "*.test.js" "*.spec.ts" "*.test.ts"

            # Using the GitHub Action (recommended)
            - uses: azure/webapps-deploy@v2
              with:
                  app-name: liquidation
                  package: "./deployment.zip"
