name: Build and deploy Node.js app to Azure Web App - liquidation

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"

            - name: Login to Azure (for tests)
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: Prepare deployment package
              run: |
                  # Create a deployment package excluding node_modules
                  zip -r deployment.zip . -x "node_modules/*" "dist/*" ".git/*"

            - name: Deploy to Azure WebApp
              id: deploy-to-webapp
              shell: bash
              run: |
                  az webapp config appsettings set --resource-group liquidation_group --name liquidation --settings SCM_DO_BUILD_DURING_DEPLOYMENT=true
                  az webapp deploy --resource-group liquidation_group --name liquidation --src-path "./deployment.zip" --type zip --remote-build true
