name: Build and deploy Node.js app to Azure Web App - liquidation

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - name: Set up Node.js version
              uses: actions/setup-node@v3
              with:
                  node-version: "22.x"

            - name: Login to Azure (for tests)
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: npm install, build, and test
              run: |
                  npm install
                  npm run build --if-present
                  npm run test --if-present

            - name: Copy static JSON files to dist directory
              run: |
                  # Create directory structure if needed
                  mkdir -p dist/json

                  # Copy all JSON files to dist directory
                  cp -r json/* dist/json/

                  # Show the final structure
                  echo "Final deployment package structure:"
                  find dist -type f | sort

                  # Show package size
                  echo "Deployment package size:"
                  du -sh dist

            # Option 1: Upload just the dist directory
            - name: Upload artifact for deployment job
              uses: actions/upload-artifact@v4
              with:
                  name: node-app
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: "Production"
            url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Download artifact from build job
              uses: actions/download-artifact@v4
              with:
                  name: node-app

            - name: Login to Azure
              uses: azure/login@v2
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            # Add deployment with retry logic instead of a simple delay
            - name: Deploy to Azure WebApp with retries
              id: deploy-to-webapp
              shell: bash
              run: |
                  MAX_RETRIES=5
                  RETRY_COUNT=0
                  DELAY_SECONDS=300
                  DEPLOYMENT_SUCCESS=false

                  while [ $RETRY_COUNT -lt $MAX_RETRIES ] && [ "$DEPLOYMENT_SUCCESS" != "true" ]; do
                    echo "Deployment attempt $((RETRY_COUNT+1)) of $MAX_RETRIES"
                    
                    if [ $RETRY_COUNT -gt 0 ]; then
                      echo "Waiting $DELAY_SECONDS seconds before next attempt..."
                      sleep $DELAY_SECONDS
                    fi
                    
                    echo "Attempting deployment to Azure App Service..."
                    if az webapp deployment source config-zip --resource-group liquidation_group --name liquidation --src $(pwd)/deployment.zip; then
                      DEPLOYMENT_SUCCESS=true
                      echo "Deployment successful!"
                      # Set output variable for the url step
                      echo "webapp-url=https://liquidation.azurewebsites.net" >> $GITHUB_OUTPUT
                    else
                      RETRY_COUNT=$((RETRY_COUNT+1))
                      echo "Deployment failed. Error code: $?"
                      
                      if [ $RETRY_COUNT -lt $MAX_RETRIES ]; then
                        echo "Will retry deployment..."
                      else
                        echo "Maximum retry attempts reached. Deployment failed."
                        exit 1
                      fi
                    fi
                  done
